cadenas/urls.py
from django.conf.urls import url

from . import views

import resumenact


urlpatterns = [
    url(r'^$', resumenact.views.index, name='index'),
    url(r'^(?P<actividad_id>[0-9]+)/$', views.lista, name='lista'),
    url(r'^registro/(?P<actividad_id>[0-9]+)/$', views.registro_cadena, name='registro'),
    url(r'^editar/(?P<cadena_id>[0-9]+)/$', views.editar, name='editar'),
    url(r'^registro_punto_muestreo/(?P<cadena_id>[0-9]+)/$', views.registro_punto_muestreo,
        name='registro_punto_muestreo'),
    url(r'^editar_punto_muestreo/(?P<punto_id>[0-9]+)/$', views.editar_punto_muestreo,
        name='editar_punto_muestreo'),
    url(r'^subir_xml_punto_muestreo/(?P<punto_id>[0-9]+)/$', views.subir_xml_punto_muestreo,
        name='subir_xml_punto_muestreo'),
]

simues/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'simues.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('resumenact.urls'), name="index"),
    url(r'^seguimiento/', include('resumenact.urls', namespace="resumenact")),
    url(r'^cadenas/', include('cadenas.urls', namespace="cadenas")),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('allauth.urls')),
]

cadenas/models.py
# -*- coding: utf-8 -*-

from django.db import models

from resumenact.models import Tterminoreferencia, Tlaboratorio, EfaActividad, Tsubmatriz, Tterminoreferenciadet, \
    Auditable, Tanalisis

from simues.settings import SIMUES_USER



class SimuesZona(models.Model):
    nombre = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesZona"'


class SimuesDatum(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesDatum"'


class SimuesGPS(models.Model):
    marca = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.marca

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesGPS"'


class SimuesTipoPunto(models.Model):
    nombre = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesTipoPunto"'

class SimuesTipoMuestra(models.Model):
    nombre = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesTipoMuestra"'


class SimuesTipoEnvase(models.Model):
    nombre = models.CharField(max_length=30, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesTipoEnvase"'


class SimuesCadenaCustodia(Auditable):
    tdr = models.ForeignKey(Tterminoreferencia, blank=True, null=True)
    tipo_matriz = models.ForeignKey(Tsubmatriz, blank=True, null=True, to_field='idsubmatriz')
    actividad = models.ForeignKey(EfaActividad, to_field='idactividad', blank=True, null=True)
    nro_orden = models.IntegerField(default=1, blank=True, null=True)
    laboratorio = models.ForeignKey(Tlaboratorio, to_field='idlaboratorio', blank=True, null=True)
    correlativo = models.CharField(max_length=40, default='SIN CORRELATIVO')
    fecha_resultados_lab =  models.DateTimeField(blank=True, null=True)
    referencia = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.correlativo

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesCadenaCustodia"'

    def analisis(self):
        """
        Devuelve el análisis del tdr de la cadena
        """
        if self.tdr:
            if Tanalisis.objects.filter(idanalisis = self.tdr.idanalisis).exists():
                return Tanalisis.objects.get(idanalisis = self.tdr.idanalisis).txanalisis
        return False

    def numero_cadenas(self):
        """
        Devuelve la cantidad de cadenas asociadas al tdr
        """
        num_cadenas = 0

        if self.tdr:
            num_cadenas = self.tdr.simuescadenacustodia_set.all().count()
        return num_cadenas


class SimuesPuntoMuestreo(Auditable):
    nombre = models.CharField(max_length=40, blank=True, null=True)
    cadena = models.ForeignKey(SimuesCadenaCustodia, blank=True, null=True)
    zona = models.ForeignKey(SimuesZona, blank=True, null=True)
    datum = models.ForeignKey(SimuesDatum, blank=True, null=True)
    gps =  models.ForeignKey(SimuesGPS, blank=True, null=True)
    tipomuestra = models.ForeignKey(SimuesTipoMuestra, blank=True, null=True)
    tipopunto =  models.ForeignKey(SimuesTipoPunto, blank=True, null=True)
    observacion = models.TextField(max_length=300, blank=True, null=True)
    envases = models.ManyToManyField(SimuesTipoEnvase, through='SimuesPuntoMuestreoEnvases')
    parametros = models.ManyToManyField(Tterminoreferenciadet,
                                        through='SimuesPuntoMuestreoTerminoReferenciaDet')
    fecha_hora = models.DateTimeField(blank=True, null=True)
    altitud = models.BigIntegerField(blank=True, null=True)
    coord_norte = models.BigIntegerField(blank=True, null=True)
    coord_este = models.BigIntegerField(blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesPuntoMuestreo"'


class SimuesUnidadMedida(models.Model):
    nombre = models.CharField(max_length=40)
    simbolo = models.CharField(max_length=40, blank=True, null=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesUnidadMedida"'


class SimuesPuntoMuestreoTerminoReferenciaDet(Auditable):
    punto = models.ForeignKey(SimuesPuntoMuestreo)
    tdrdet = models.ForeignKey(Tterminoreferenciadet,    to_field='idtermrefdet')
    unidad_medida = models.ForeignKey(SimuesUnidadMedida, blank=True, null=True)
    check = models.NullBooleanField()
    valor = models.FloatField(blank=True, null=True)

    def __unicode__(self):
        return self.punto.nombre

    class Meta:
        unique_together = (("punto", "tdrdet" ),)
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesPuntoMuestre0bc3"'


class SimuesPuntoMuestreoEnvases(Auditable):
    punto = models.ForeignKey(SimuesPuntoMuestreo)
    envase= models.ForeignKey(SimuesTipoEnvase)
    numero = models.IntegerField(blank=True, null=True  )

    class Meta:
        unique_together = (("punto", "envase"),)
        db_table = '"' + SIMUES_USER +'"'+ '."cadenas_SimuesPuntoMuestre0ad9"'

    def __unicode__(self):
        return self.punto.nombre + " " + self.envase.nombre + " " + str(self.numero)

cadenas/views.py
# -*- coding: utf-8 -*-
from datetime import date


from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.forms.formsets import formset_factory

from resumenact.models import EfaActividad, Tterminoreferencia, Tterminoreferenciadet, Tsubmatriz, Tlaboratorio, Tsector
from .models import SimuesCadenaCustodia, SimuesTipoMuestra, SimuesPuntoMuestreo, SimuesTipoEnvase, \
    SimuesPuntoMuestreoEnvases, SimuesPuntoMuestreoTerminoReferenciaDet,SimuesUnidadMedida

from .forms import RegistroCadenasForm, RegistroPuntoMuestra, EnvasesForm, ParametrosForm, SubirPuntoMuestraForm



@login_required
def lista(request, actividad_id):
    """ Pantalla inicial del modulo de Seguimiento donde se buscan las actividades
    """

    # Obtenemos la actividad y con esta las cadenas asociadas
    actividad = get_object_or_404(EfaActividad, idactividad=actividad_id)
    cadenas = SimuesCadenaCustodia.objects.filter(actividad = actividad).order_by('nro_orden')

    return render(request, 'cadenas/lista.html', {'cadenas':cadenas, 'actividad':actividad})


@login_required
def registro_cadena(request, actividad_id):
    """  Esta vista se utiliza para crear una nueva cadena de custodia
    """

    actividad = get_object_or_404(EfaActividad, idactividad=actividad_id)
    mostrar = False

    if request.method == 'POST':

         # Crear una instancia del formulario con el Post y la actividad para obtener
         # los laboratorios asociados
        form = RegistroCadenasForm(request.POST, actividad=actividad)

        if form.is_valid():

            # Obtenemos el tdr de la cadena y el número de cadenas relacionadas a ese tdr
            tdr = None
            num_cadenas = None
            if form.cleaned_data['tdr']:
                if Tterminoreferencia.objects.filter(txcodigo=form.cleaned_data['tdr']).exists():
                    tdr = Tterminoreferencia.objects.get(txcodigo=form.cleaned_data['tdr'])
                    num_cadenas = len(tdr.simuescadenacustodia_set.all()) + 1

            tipo_matriz = None
            if form.cleaned_data['tipo_matriz']:
                tipo_matriz = Tsubmatriz.objects.get(idsubmatriz=form.cleaned_data['tipo_matriz'].idsubmatriz)

            # Si se ha elegido un laboratorio en el combo de laboratorios y si existe ese laboratorio en la BD
            laboratorio = None
            if (form.cleaned_data['laboratorio'] and
                Tlaboratorio.objects.filter(idlaboratorio=form.cleaned_data['laboratorio'].idlaboratorio).exists()):
                laboratorio = Tlaboratorio.objects.get(idlaboratorio=form.cleaned_data['laboratorio'].idlaboratorio)

            # Creamos la cadena con los parámetros necesarios.
            # El número de orden es la cantidad de cadenas de custodia pertenecientes
            # a un tdr mas 1
            cadena = SimuesCadenaCustodia(tdr = tdr,
                                          actividad = actividad,
                                          tipo_matriz=tipo_matriz,
                                          nro_orden=num_cadenas,
                                          referencia = form.cleaned_data['referencia'],
                                          laboratorio = laboratorio,
                                          fecha_resultados_lab = form.cleaned_data['fecha_resultados_lab'])
            cadena.save()

            # Agregamos el numero correlativo
            cadena.correlativo = str(cadena.id)+"-"+str(date.today().year)+"-"+cadena.actividad.idsector.txsector

            cadena.created_by = request.user
            cadena.modified_by = request.user

            cadena.save()

            # Mensaje para saber que se guardo con éxito
            messages.success(request, 'La Cadena de Custodia se grabó satisfactoriamente')

            # Una vez guardado se pasa a editar
            return redirect('cadenas:editar', cadena_id=cadena.id)

    else:
        # Si recién se ingresa en la cadena
        form = RegistroCadenasForm(actividad=actividad)

    return render(request, 'cadenas/registro.html', {'form':form, 'mostrar':mostrar})


@login_required
def editar(request, cadena_id):
    """
    Pantalla donde se editan las cadenas de custodia
    """

    cadena = get_object_or_404(SimuesCadenaCustodia, id=cadena_id)
    mostrar = False

    puntos_muestreo = SimuesPuntoMuestreo.objects.filter(cadena=cadena)

    if len(puntos_muestreo) > 0:
        mostrar = True

    # Se crea una instancia del formulario y se guardan los nuevos valores
    if request.method == 'POST':
        form = RegistroCadenasForm(request.POST, actividad=cadena.actividad, cadena=cadena)

        if form.is_valid():

            # Obtenemos el tdr de la cadena y el número de cadenas relacionadas a ese tdr
            if cadena.tdr != form.cleaned_data['tdr']:
                if Tterminoreferencia.objects.filter(idtermref=form.cleaned_data['tdr'].idtermref).exists():
                    cadena.tdr = Tterminoreferencia.objects.get(idtermref=form.cleaned_data['tdr'].idtermref)
                    cadena.nro_orden = len(cadena.tdr.simuescadenacustodia_set.all()) + 1
                else:
                    cadena.tdr = None
                    cadena.nro_orden = None

            # Obtenemos el tipo de muestra
            if cadena.tipo_matriz != form.cleaned_data['tipo_matriz']:
                if Tsubmatriz.objects.filter(idsubmatriz=form.cleaned_data['tipo_matriz'].idsubmatriz).exists():
                    cadena.tipo_matriz = Tsubmatriz.objects.get(
                        idsubmatriz=form.cleaned_data['tipo_matriz'].idsubmatriz)

            cadena.referencia = form.cleaned_data['referencia']
            cadena.laboratorio = form.cleaned_data['laboratorio']
            cadena.fecha_resultados_lab = form.cleaned_data['fecha_resultados_lab']

            cadena.modified_by = request.user

            cadena.save()

            # Mensaje para saber que se guardo con éxito
            messages.success(request, 'La Cadena de Custodia se grabó satisfactoriamente')
    else:

        form = RegistroCadenasForm(actividad=cadena.actividad, cadena=cadena)

    return render(request, 'cadenas/registro.html', {'form':form, 'mostrar':mostrar,
                                                     'puntos_muestreo':puntos_muestreo, 'cadena':cadena})


@login_required
def registro_punto_muestreo(request, cadena_id):
    """
    Vista donde se guarda un nuevo punto de muestreo
    """

    cadena = get_object_or_404(SimuesCadenaCustodia, id=cadena_id)
    mostrar = False

    if request.method == 'POST':

        form_punto = RegistroPuntoMuestra(request.POST)

        if form_punto.is_valid():

            # Se crea y se guarda el punto de muestreo
            punto_muestreo = SimuesPuntoMuestreo(nombre=form_punto.cleaned_data['nombre'],
                                                 cadena=cadena,
                                                 zona=form_punto.cleaned_data['zona'],
                                                 datum=form_punto.cleaned_data['datum'],
                                                 gps=form_punto.cleaned_data['gps'],
                                                 tipomuestra=form_punto.cleaned_data['tipo_muestra'],
                                                 tipopunto=form_punto.cleaned_data['tipo_punto'],
                                                 observacion=form_punto.cleaned_data['observacion'],
                                                 fecha_hora=form_punto.cleaned_data['fecha_hora'],
                                                 altitud=form_punto.cleaned_data['altitud'],
                                                 coord_norte=form_punto.cleaned_data['coord_norte'],
                                                 coord_este=form_punto.cleaned_data['coord_este'])

            punto_muestreo.created_by = request.user
            punto_muestreo.modified_by = request.user

            punto_muestreo.save()

            # Mensaje para saber que se guardo con éxito
            messages.success(request, 'El punto de muestreo se grabó satisfactoriamente',
                             extra_tags='punto')

            mostrar = True

            return redirect('cadenas:editar_punto_muestreo', punto_id=punto_muestreo.id)

    else:

        form_punto = RegistroPuntoMuestra()

    return render(request, 'cadenas/registro_punto_muestreo.html', {'form_punto':form_punto,
                                                                    'mostrar':mostrar})


@login_required
def editar_punto_muestreo(request, punto_id):
    """
    Vista donde se edita el punto de muestreo
    """

    punto_muestreo = get_object_or_404(SimuesPuntoMuestreo, id=punto_id)
    envases = SimuesTipoEnvase.objects.all()
    detalle_envases = SimuesPuntoMuestreoEnvases.objects.filter(punto=punto_muestreo)

    # Se obtienen los detalles de los tdrs guardados y sus detalles
    detalles_tdrs = Tterminoreferenciadet.objects.filter(idtermref=punto_muestreo.cadena.tdr,
                                                    idsubmatriz=punto_muestreo.cadena.tipo_matriz)

    # Se obtienen los detalles de los parametros y Puntos de Referencia
    detalles_parametros = SimuesPuntoMuestreoTerminoReferenciaDet.objects.filter(punto=punto_muestreo)

    # Se vuelve True para que se muestren los formularios que no se ven en Registrar Punto de Muestreo
    mostrar = True

    form_punto = RegistroPuntoMuestra(punto_muestreo=punto_muestreo)
    form_subir_xml = SubirPuntoMuestraForm()

    # Se crea el formulario donde se ingresan el número de envases por tipo de envase
    form_envases = EnvasesForm(envases=envases, detalle_envases=detalle_envases)

    # Creacion del formset de Parámetros, la data inicial es una lista de diccionarios
    # donde cada diccionario es la data inicial de uno de los formularios del formset

cadenas/templates/cadenas/lista.html
{% extends "main.html" %}


{% block title %}Lista de Cadenas de Custodia{% endblock %}

{% block subtitulo %}Lista de Cadenas de Custodia{% endblock %}



{% block cabecera %}

<p>Unidad: {{actividad.idunidadoperativa}}</p>
<p>Actividad: {{actividad.idsubunidadoperativa.actividad}}</p>

{% endblock cabecera %}

{% block form %}
{% endblock form %}

{% block content %}

<table class="table table-bordered">
    <tr>
        <th>Nro de Orden</th>
        <th>TDR</th>
        <th>Correlativo</th>
        <th>Laboratorio</th>
        <th>Tarea (Análisis)</th>
        <th>Editar</th>
    </tr>
    {% for cadena in cadenas %}
    <tr>
        <td>{% if cadena.tdr %}
                {{cadena.nro_orden}} - {{cadena.numero_cadenas}}
            {% else %}
                No tiene # de orden
            {% endif %}
        </td>
        <td>{{cadena.tdr}}</td>
        <td>{{cadena.correlativo}}</td>
        <td>{{cadena.laboratorio}}</td>
        <td>
        {% if cadena.analisis %}
           {{cadena.analisis}}
        {% else %}
           No tiene análisis
        {% endif %}
        </td>
        <td>
            <a href="{% url 'cadenas:editar' cadena.id %}">Editar</a>
        </td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'cadenas:registro' actividad.idactividad %}">Nueva Cadena de Custodia</a>

{% endblock %}

cadenas/templates/cadenas/registro.html
{% extends "main.html" %}


{% block title %} Formulario de Registro de Cadenas de Custodia{% endblock %}

{% block subtitulo %}Formulario de Registro de Cadenas de Custodia{% endblock %}


{% block form %}
{{block.super}}
{%endblock%}


{% block content %}

{% if cadena %}

<a href="{% url 'cadenas:registro_punto_muestreo' cadena.id %}">Nuevo Punto de Muestreo </a>

{% endif %}

{%if mostrar%}

<h3>Muestras</h3>


<table class="table table-bordered">
    <tr>
        <th>Punto de Muestreo</th>
        <th>Tipo de punto</th>
        <th>Tipo de Muestra</th>
        <th>Fecha/Hora</th>
        <th>Editar</th>
    </tr>
    {% for punto_muestreo in puntos_muestreo %}
    <tr>
        <td>{{punto_muestreo.nombre}}</td>
        <td>{{punto_muestreo.tipopunto}}</td>
        <td>{{punto_muestreo.tipomuestra}}</td>
        <td>{{punto_muestreo.fecha_hora}}</td>
        <td>
            <a href="{% url 'cadenas:editar_punto_muestreo' punto_muestreo.id %}">Editar</a>
        </td>
    </tr>
    {% endfor %}

</table>
{% endif %}



{% endblock %}

cadenas/templates/cadenas/registro_punto_muestreo.html
{% extends "main.html" %}

{% block title %}Formulario de Registro de Puntos de Muestreo{% endblock %}

{% block subtitulo %}Formulario de Registro de Puntos de Muestreo{% endblock %}

{% block form %}
{{ form_punto.media }}


<form action="" method="post">
{% csrf_token %}
<table>
    {% for field in form_punto.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
</table>

     {% if messages %}
        {% for message in messages %}
            {% if 'punto' in message.tags %}
                <div class="message">{{ message }}</div>
            {% endif %}
        {% endfor %}
     {% endif %}

<input type="submit" value="Guardar" name="form_punto"/>
</form>


{% if mostrar %}

<h3>Ingresar Número de Envases</h3>

<form action="" method="post">
{% csrf_token %}
    <table>
    {% for field in form_envases.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
    </table>

     {% if messages %}
        {% for message in messages %}
            {% if 'envases' in message.tags %}
                <div class="message">{{ message }}</div>
            {% endif %}
        {% endfor %}
     {% endif %}

<input type="submit" value="Guardar" name="form_envases"/>
</form>



{% if formset_parametros %}

<h3>Subir archivo Xml con los valores de los parámetros</h3>

<form action="{% url 'cadenas:subir_xml_punto_muestreo' punto.id %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <table>
    {% for field in form_subir_xml.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
    </table>

     {% if messages %}
        {% for message in messages %}
            {% if 'subido' in message.tags %}
                <div class="message">{{ message }}</div>
            {% endif %}
        {% endfor %}
     {% endif %}


<input type="submit" value="Subir" name="form_subir_xml"/>
</form>


<h3>Ingresar valores de los Parámetros</h3>

<form action="" method="post">
{% csrf_token %}

    <table>
    {{formset_parametros.as_table}}
    </table>

     {% if messages %}
        {% for message in messages %}
            {% if 'parametros' in message.tags %}
                <div class="message">{{ message }}</div>
            {% endif %}
        {% endfor %}
     {% endif %}

<input type="submit" value="Guardar" name="form_parametros"/>
</form>



{% endif %}

{% endif %}
{% endblock form %}

{% block content %}

{% endblock %}