cadenas/urls.py
from django.conf.urls import url

from . import views

import resumenact


urlpatterns = [
    url(r'^$', resumenact.views.index, name='index'),
    url(r'^(?P<actividad_id>[0-9]+)/$', views.lista, name='lista'),
    url(r'^registro/(?P<actividad_id>[0-9]+)/$', views.registro_cadena, name='registro'),
    url(r'^editar/(?P<cadena_id>[0-9]+)/$', views.editar, name='editar'),
    url(r'^registro_punto_muestreo/(?P<cadena_id>[0-9]+)/$', views.registro_punto_muestreo,
        name='registro_punto_muestreo'),
    url(r'^editar_punto_muestreo/(?P<punto_id>[0-9]+)/$', views.editar_punto_muestreo,
        name='editar_punto_muestreo'),
    url(r'^subir_xml_punto_muestreo/(?P<punto_id>[0-9]+)/$', views.subir_xml_punto_muestreo,
        name='subir_xml_punto_muestreo'),
]

resumenact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro/$', views.index, name='index'),
    url(r'^registro/(?P<actividad_id>[0-9]+)/$', views.registro, name='registro'),
    url(r'^elegir_cargo_inspectores/(?P<actividad_id>[0-9]+)/$', views.elegir_cargo_inspectores,
        name='elegir_cargo_inspectores'),

    # Ajax urls
    url(r'^obtener_unidades/(?P<administrado_id>[\w-]+)/$', views.obtener_unidades, name='obtener_unidades'),
    url(r'^obtener_subtipos_supervision/(?P<tiposupervision_id>[\w-]+)/$',
        views.obtener_subtipos_supervision, name='obtener_subtipos_supervision')


]

simues/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'simues.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('resumenact.urls'), name="index"),
    url(r'^seguimiento/', include('resumenact.urls', namespace="resumenact")),
    url(r'^cadenas/', include('cadenas.urls', namespace="cadenas")),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('allauth.urls')),
]

resumenact/views.py
# -*- coding: utf-8 -*-

import operator

from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q

from .models import EfaActividad, SimuesProceso, SimuesProcesoSegActividadDET, SimuesSegActividad,\
                    DATE, INTEGER, BOOL, Tterminoreferencia, Tsector, Tcargosup, Tsubtipsup, \
                    SimuesSeguimientoSupervisores, Tunidadoperativa
from .forms import BusquedaForm, RegistroForm, ElegirCargoInspectoresForm

CODINSPECTORLIDER = 'CRS002'
CODINSPECTOR = 'CRS005'

def get_or_none(classmodel, **kwargs):
    try:
        return classmodel.objects.get(**kwargs)
    except classmodel.DoesNotExist:
        return None


@login_required
def index(request):
    """ Pantalla inicial del modulo de Seguimiento donde se buscan las actividades
    """

    # Obtiene la lista de grupos del usuario
    lista_grupos = []

    # Si no hay grupos en el usuario no lo deja loguearse
    if request.user.groups.all().count() > 0:
        for group in request.user.groups.all():
            lista_grupos.append(Q(txsector=group))

        # Obtiene los ids de los grupos del usuario
        idsector = Tsector.objects.filter(reduce(operator.or_, lista_grupos))
    else:
        messages.success(request, 'El usuario no pertenece a un grupo.', extra_tags='login')
        logout(request)
        return redirect('accounts/login/')


    if request.method == 'GET':
        # Crear una instancia del formulario
        form = BusquedaForm(request.GET)

        # Como hemos agregado a mano las las opciones con jquery
        # las agregamos a mano en el formulario antes de ser validado
        # http://stackoverflow.com/questions/28339713/while-using-ajax-with-django-form-getting-error-select-a-valid-choice-that-is
        #unidad = request.GET['unidad']
        #unidad = Tunidadoperativa.objects.get(idunidadoperativa = unidad)
        #form.fields['unidad'].choices = [(unidad.idunidadoperativa, unidad.txnombreunidad)]

        #print form['unidad']

        # Chequear si es válido

        if form.is_valid():

            mostrar = True

            # Lista las actividades por el grupo al que pertenece el usuario
            actividades = EfaActividad.objects.select_related(
                'idsubunidadoperativa__idunidadoperativa__txnombreunidad', 'idsubtipsup__txsubtipsup',
                'idsubtipsup__idtipsup__txtipsup', 'idadministrado__razonsocial', 'simuessegactividad__id'
            ).only('codactividad', 'fechaini','fechafin', 'idsubunidadoperativa__idunidadoperativa__txnombreunidad',
                   'idsubtipsup__txsubtipsup',
                   'idsubtipsup__idtipsup__txtipsup', 'idadministrado__razonsocial', 'simuessegactividad__id'
            ).filter(idsector_id__in = idsector)

            # Buscamos de acuerdo a los criterios ingresados en el formulario
            if form.cleaned_data['cuc']:
                actividades = actividades.filter(codactividad__contains=form.cleaned_data['cuc'])
            if form.cleaned_data['fecha_ini']:
                actividades = actividades.filter(fechaini__gte=form.cleaned_data['fecha_ini'])
            if form.cleaned_data['fecha_fin']:
                actividades = actividades.filter(fechafin__lte=form.cleaned_data['fecha_fin'])
            if form.cleaned_data['administrado']:
                actividades = actividades.filter(idadministrado=form.cleaned_data['administrado'])
            if form.cleaned_data['unidad']:
                actividades = actividades.filter(idunidadoperativa=form.cleaned_data['unidad'].idunidadoperativa)
            if form.cleaned_data['tdr']:
                if Tterminoreferencia.objects.filter(idtermref=form.cleaned_data['tdr'].idtermref).exists():
                    tdr = Tterminoreferencia.objects.get(idtermref=form.cleaned_data['tdr'].idtermref)
                    actividades = actividades.filter(idactividad=tdr.idactividad.idactividad)
            if form.cleaned_data['tipo_supervision']:
                actividades = actividades.filter(idtipsup_id = form.cleaned_data['tipo_supervision'])
            if form.cleaned_data['sub_tipo_supervision']:
                actividades = actividades.filter(idsubtipsup_id = form.cleaned_data['sub_tipo_supervision'])


            return render(request, 'resumenact/index.html',
                          {'form':form, 'actividades':actividades, 'mostrar':mostrar})

    # Si no es POST entonces se crea el formulario en blanco
    else:
        form = BusquedaForm()

    return render(request, 'resumenact/index.html', {'form':form})


@login_required
def obtener_unidades(request, administrado_id):
    """
    Función donde se devuelven las unidades relacionadas al administrado
    """

    combo_unidad_html = ""

    if Tunidadoperativa.objects.filter(idadministrado = administrado_id).exists():
        unidades = Tunidadoperativa.objects.filter(idadministrado = administrado_id)

        for unidad in unidades:
            combo_unidad_html += '<option value="'+str(unidad.idunidadoperativa)+'">'+unidad.txnombreunidad+'</option>'
    else:
        combo_unidad_html = "<option value='' selected='selected'>No se encontraron resultados</option>"


    return HttpResponse(combo_unidad_html)


@login_required
def obtener_subtipos_supervision(request, tiposupervision_id):
    """
    Función donde se devuelven las unidades relacionadas al administrado
    """

    combo_subtipo_html = ""

    if Tsubtipsup.objects.filter(idtipsup = tiposupervision_id).exists():
        subtipos = Tsubtipsup.objects.filter(idtipsup = tiposupervision_id)

        for subtipo in subtipos:
            combo_subtipo_html += '<option value="'+str(subtipo.idsubtipsup)+'">'+subtipo.txsubtipsup+'</option>'
            print combo_subtipo_html
    else:
        combo_unidad_html = "<option value='' selected='selected'>No se encontraron resultados</option>"


    return HttpResponse(combo_subtipo_html)



@login_required
def registro(request, actividad_id):
     """ Formulario de registro de Seguimiento de Actividades """

     # Se elige el tipo de inspector líder de la tabla de Cargos de Supervisiones
     tipo_inspector_lider = Tcargosup.objects.get(idcargosup=CODINSPECTORLIDER)
     # Se elige el tipo de inspector de la tabla de Cargos de Supervisiones
     tipo_inspector = Tcargosup.objects.get(idcargosup=CODINSPECTOR)

     # Lee los valores de Proceso
     procesos = SimuesProceso.objects.all().order_by('id')

     # Si no obtiene el id de la actividad redirige al error 404
     actividad = get_object_or_404(EfaActividad, idactividad=actividad_id)

     # Asignamos los valores iniciales
     supervisores_actividad = SimuesSeguimientoSupervisores.objects.filter(actividad=actividad)

     supervisores = {}

     if supervisores_actividad.filter(cargo=tipo_inspector).exists():
         supervisores['inspector'] = supervisores_actividad.get(cargo=tipo_inspector)
     if supervisores_actividad.filter(cargo=tipo_inspector_lider).exists():
         supervisores['inspector_lider'] = supervisores_actividad.get(cargo=tipo_inspector_lider)

     # Inicializamos el formulario para Elegir los cargos de los inspectores asociados a la actividad
     form_elegir = ElegirCargoInspectoresForm(actividad=actividad, supervisores=supervisores)

     if request.method == 'POST':

         # Crear una instancia del formulario con los parametros extras
         form_seguimiento = RegistroForm(request.POST, extra = procesos)

         # Chequear si es válido
         if form_seguimiento.is_valid():

             if SimuesSegActividad.objects.filter(id=actividad).exists():
                 segact = SimuesSegActividad.objects.get(id=actividad)

                 # Iteramos sobre los campos del formulario y guardamos los valores dependiendo del tipo de dato
                 for (nombre, valor) in form_seguimiento.procesos():
                     # Comprobamos si existe el Proceso en la bd antes de obtenerlo
                     if SimuesProceso.objects.filter(id = nombre).exists():
                         proceso = SimuesProceso.objects.get(id = nombre)

                         # Comprobamos si existe el detalle del proceso y seguimiento.
                         # Si existe guardamos el valor del campo
                         if SimuesProcesoSegActividadDET.objects.filter(idsegactividad=segact,
                                                                        idproceso=proceso).exists():
                             detalle = SimuesProcesoSegActividadDET.objects.get(idsegactividad=segact,
                                                                                idproceso=proceso)

                             grabar = False
                             if proceso.tipo_dato == DATE  and detalle.fecha != form_seguimiento.cleaned_data[str(nombre)]:
                                 detalle.fecha = form_seguimiento.cleaned_data[str(nombre)]
                                 grabar = True
                             elif proceso.tipo_dato == INTEGER and detalle.num != form_seguimiento.cleaned_data[str(nombre)]:
                                 detalle.num = form_seguimiento.cleaned_data[str(nombre)]
                                 grabar = True
                             elif proceso.tipo_dato == BOOL and detalle.sino != form_seguimiento.cleaned_data[str(nombre)]:
                                 detalle.sino = form_seguimiento.cleaned_data[str(nombre)]
                                 grabar = True

                             if grabar:
                                 detalle.modified_by = request.user
                                 detalle.save()


                 # Mensaje para saber que se guardo con éxito
                 messages.success(request, 'Las actividades de Supervisión se grabaron satisfactoriamente',

resumenact/templates/resumenact/index.html
{% extends "main.html" %}

{% load staticfiles %}

{% block title %}
Formulario de Búsqueda de Actividades de Supervisión
{% endblock %}


{% block script_propio%}
<!-- Css Propio-->
<link href="{% static 'css/form_busqueda.css' %}" rel="stylesheet">
{% endblock %}


{%block subtitulo %} Formulario de Búsqueda de Actividades de Supervisión{% endblock %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


   {% block form %}
    <form action="" method="get" class="form-vertical">

            {% include "form_snippet.html" with form=form %}

            <button type="submit" class="btn btn-primary"/>
            {% block nombreboton %} Buscar{% endblock %}
            </button>
    </form>
    {% endblock form%}


{% block content %}
{% if mostrar %}

<br>

{% if actividades.count = 0 %}
<div class="message">No se encontraron Resultados</div>
{% endif %}

<h2 class="sub-header">Actividades de Muestreo</h2>

<table class="table table-bordered">
    <tr>
        <th>CUC</th>
        <th>Tipo de Supervisión</th>
        <th>SubTipo de Supervisión</th>
        <th>Fecha Inicial</th>
        <th>Fecha Final</th>
        <th>Administrado</th>
        <th>Unidad</th>
        <th>Seguimiento Actividad</th>
        <th>Cadenas de Custodia</th>
    </tr>

    {% for actividad in actividades %}
    <tr>

        <td>{{actividad.codactividad}}</td>
        <td>{{actividad.idsubtipsup.idtipsup.txtipsup}}</td>
        <td>{{actividad.idsubtipsup.txsubtipsup}}</td>
        <td>{{actividad.fechaini.date}}</td>
        <td>{{actividad.fechafin.date}}</td>
        <td>{{actividad.idadministrado.razonsocial}}</td>
        <td>{{actividad.idsubunidadoperativa.idunidadoperativa.txnombreunidad}}</td>

        <td>
            <a href="{% url 'resumenact:registro' actividad.idactividad %}">
            {% if actividad.simuessegactividad.id %}
               Editar
            {% else %}
                Nuevo
            {% endif %}
            </a>
        </td>
        <td>
            <a href="{% url 'cadenas:lista' actividad.idactividad %}">Cadenas
            </a>
        </td>
    </tr>
    {% endfor %}
</table>

{% endif %}

{% endblock %}

{% block script_propios %}
{% load staticfiles %}
<script src="{% static 'js/ajax_form_busqueda.js' CSRF_TOKEN={{ csrf_token }} %}"></script>
{% endblock %}

{%comment%}
{%endcomment%}

resumenact/templates/resumenact/registro.html
{% extends "main.html" %}

{% block title %}
Formulario de Registro del Seguimiento de Actividades de Supervisión
{% endblock %}

{%block subtitulo %}Seguimiento de Actividades de Supervisión {% endblock %}

{% block cabecera %}

<table>

<tr><td><b>CUC:</b></td> <td>{{actividad.codactividad}}</td></tr>
<tr><td><b>Unidad:</b></td> <td>{{actividad.idunidadoperativa}}</td></tr>
<tr><td><b>Actividad:</b></td> <td>{{actividad.idsubunidadoperativa.actividad}}</td></tr>
<tr><td><b>Fecha Inicial:</b></td> <td>{{actividad.fechaini}}</td></tr>
<tr><td><b>Fecha Fin:</b></td> <td>{{actividad.fechafin}}</td></tr>
<tr><td><b>Tipo Supervisión:</b></td> <td>{{actividad.idtipsup.txtipsup}}</td></tr>
<tr><td><b>Sub Tipo Supervisión:</b></td> <td>{{actividad.idsubtipsup.txsubtipsup}}</td></tr>
<tr><td><b>TDRs:</b></td>

    <td> {% for tdr in actividad.tdrs %}

            {{tdr}},

         {% endfor %}
    </td>
</tr>

</table>
{% endblock cabecera %}

{% block form %}
{{ form_seguimiento.media }}


<form action="{% url 'resumenact:elegir_cargo_inspectores' actividad.idactividad %}"
                                        method="post" enctype="multipart/form-data">
{% csrf_token %}

<table>
    {% for field in form_elegir.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
</table>

 {% if messages %}
    {% for message in messages %}
        {% if 'inspector' in message.tags %}
            <div class="message">{{ message }}</div>
        {% endif %}
    {% endfor %}
 {% endif %}

    <input type="submit" value="Guardar" name="form_elegir"/>
</form>


<form action="" method="post">
{% csrf_token %}
<table>
    {% for field in form_seguimiento.visible_fields %}
        <tr>
            <td>{{ field.label_tag }}</td>
            <td>{{ field }}</td>
            <td>{{ field.errors }}</td>
        </tr>
    {% endfor %}
</table>

     {% if messages %}
        {% for message in messages %}
            {% if 'seguimiento' in message.tags %}
                <div class="message">{{ message }}</div>
            {% endif %}
        {% endfor %}
     {% endif %}

<input type="submit" value="Guardar" name="form"/>
</form>

{% endblock form %}